version: '3'


services:
  fdrbot:
    build: .
    environment:
      - TOKEN=${TOKEN}
      - MONGO_URL=${MONGO_URL}
      - REDIS_URL=redis://redis:6379
      - OWNER_IDS=${OWNER_IDS:-}

      - CDN_URL=${CDN_URL:-"http://cdn.fdrbot.com"}

      - LAVALINK_NODE_IP=lavalink
      - LAVALINK_NODE_PORT=2333
      - LAVALINK_NODE_PASSWORD=${LAVALINK_NODE_PASSWORD:-}
    restart: always
    container_name: fdrbot
    depends_on:
      - lavalink
      - redis
      # - db  # (if you want to use a database)
  lavalink:
    image: fredboat/lavalink:master
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./logs:/opt/Lavalink/logs
    ports:
      - 2333:2333
    hostname: lavalink
    container_name: lavalink

  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    
  # db:
  #   image: mongo
  #   volumes:
  #     - $HOME/data/mongodb:/data/db
  #   ports:
  #     - 27019:27017
  #   # network_mode: host
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: root_password
