version: '3'


services:
  fdrbot:
    build: .
    volumes:
      - ./configuration.yml:/opt/fdrbot/configuration.yml
    ports:
      - 8080:8080
    environment:
      - MONGODB_URI=mongodb+srv://fdrbot:kncz2yeoMZ1rMoqL@cluster0.cruh9.mongodb.net/admin?authSource=admin&replicaSet=atlas-12nh4s-shard-0&readPreference=primary&ssl=true
    links:
      - db
      - lavalink

  lavalink:
    image: fredboat/lavalink:master
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    ports:
      - 2333:2333
    restart: always
    network_mode: host

  db:
    image: mongo
    volumes:
      - .\mongodb:/data/db
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
    network_mode: host